projeto pasando tudo
betrybe/sd-0x-project-trybewallet-rubric pull request #1
Opened 2021-02-01 19:24 UTC by brunobatista25

2021-08-10 17:33 UTC, StoneHg commented
Eu acho que pode fechar esse PR. Só confirmar com o @icaroharry

2021-08-10 17:38 UTC, gabriellukke commented on src/pages/Login.js
> +      <input
Acho que seria válido controlar este input com o estado do componente, seguindo as boas práticas do React.

2021-08-10 17:38 UTC, gabriellukke commented on src/pages/Login.js
> +      <form onSubmit={ this.submitLogin }>
Utilizando o input controlado seria interessante utilizar o evento onClick na tag button com type="button", já que não precisamos das informações que a tag form traz, pois temos o estado do componente.

2021-08-10 17:38 UTC, gabriellukke commented on src/components/Form.js
> +  render1() {
Seria ideal utilizar o nome mais descritivo para o método ao invés de utilizar uma numeração.

2021-08-11 01:13 UTC, henriquejensen requested changes

2021-08-11 01:13 UTC, henriquejensen commented on src/components/Form.js
> +          <select
O select é utilizado 3 vezes no código, criar um componente dele para reutilizacao de codigo

2021-08-11 01:13 UTC, henriquejensen commented on src/components/Form.js
> +          <label htmlFor="tag">
Essa label faz parte do select, nao deve estar separado esse codigo

2021-08-11 01:13 UTC, henriquejensen commented on src/components/Form.js
> +        <div>
div desnecessaria no codigo

2021-08-11 01:13 UTC, henriquejensen commented on src/components/Header.js
> +            { total.reduce((a, c) => a + c.exchangeRates[c.currency].ask * c.value, 0)
Esse código pode ser colocado numa funcao helper

2021-08-11 01:13 UTC, henriquejensen commented on src/components/Table.js
> +    const convValue = Math.round(ask * value * 100) / 100;
Essa logica pode ser extraida para uma funcao `helper`

2021-08-11 01:13 UTC, henriquejensen commented on src/actions/index.js
> +  convValue,
esse valor não esta sendo utilizado no reducer

2021-08-11 01:13 UTC, henriquejensen commented on src/pages/Login.js
> +      <form onSubmit={ this.submitLogin }>
O ideal Gabriel é utilizar o onSubmit mesmo, ja que ele utiliza a acessibilidade e pode ser disparado via ENTER no teclado

2021-10-05 11:37 UTC, gabriellukke approved these changes

2021-10-06 12:18 UTC, merged